### ISSUE TITLE
[BUG] Plugin dies when vdc.log.old already exists

### ISSUE THREAD

**Issue by flashfingaz** [nwesterhausen/valheim-discordconnector#315]
**Describe the issue**
When vdc.log.old already exists, the plugin dies with an error

**Expected behavior**
plugin should move old logfile to vdc.log.1, vdc.log.2, vdc.log.3 (at least should not die when vdc.log.old already exists)

**Configuration**
`{"Config.Main":{"discord":{"defaultWebhookUsernameOverride":"","webhook":"REDACTED","webhookEvents":"ALL","webhookUsernameOverride":"","webhookAvatarOverride":"","webhook2":"unset","webhook2Events":"ALL","webhook2UsernameOverride":"","webhook2AvatarOverride":"","logDebugMessages":"False","fancierMessages":"True","ignoredPlayers":"","ignoredPlayersList":[],"ignoredPlayersRegex":"","allowMentionsHereEveryone":"False","allowMentionsAnyRole":"True","allowMentionsAnyUser":"True","allowedRoleMentions":"","allowedRoleMentionsList":[],"allowedUserMentions":"","allowedUserMentionsList":[]},"collectStatsEnabled":"True","sendPositionsEnabled":"True","announcePlayerFirsts":"True","playerLookupPreference":"PlayerId"},"Config.Messages":{"Messages.Server":{"launchMessage":"Server is starting up.","startMessage":"Server has started!","stopMessage":"Server is stopping.","shutdownMessage":"Server has stopped!","savedMessage":"The world has been saved.","serverNewDayMessage":"Day Number %DAY_NUMBER%"},"Messages.Player":{"joinMessage":"%PLAYER_NAME% has joined.","deathMessage":"%PLAYER_NAME% has died.","leaveMessage":"%PLAYER_NAME% has left.","pingMessage":"%PLAYER_NAME% pings the map.","shoutMessage":"%PLAYER_NAME% shouts **%SHOUT%**."},"Messages.PlayerFirsts":{"joinMessage":"%PLAYER_NAME% has joined.","deathMessage":"%PLAYER_NAME% has died.","leaveMessage":"%PLAYER_NAME% has left.","pingMessage":"%PLAYER_NAME% pings the map.","shoutMessage":"%PLAYER_NAME% shouts **%SHOUT%**."},"Messages.Events":{"eventStartMessage":"**Event**: %EVENT_MSG%","eventPausedMessage":"**Event**: %EVENT_END_MSG% — for now! (Currently paused due to no players in the event area.)","eventResumedMessage":"**Event**: %EVENT_START_MSG%","eventStopMessage":"**Event**: %EVENT_MSG%"},"Messages.LeaderBoards":{"leaderBoardTopPlayersMessage":"Top %N% Player Leader Boards:","leaderBoardBottomPlayersMessage":"Bottom %N% Player Leader Boards:","leaderBoardHighestPlayerMessage":"Top Performer","leaderBoardLowestPlayerMessage":"Bottom Performer"}},"Config.Toggles":{"Toggles.Messages":{"launchMessageEnabled":"True","loadedMessageEnabled":"True","stopMessageEnabled":"True","shutdownMessageEnabled":"True","chatShoutEnabled":"True","chatPingEnabled":"True","playerJoinEnabled":"True","playerLeaveEnabled":"True","playerDeathEnabled":"True","eventStartEnabled":"True","eventPausedEnabled":"True","eventStoppedEnabled":"True","eventResumedEnabled":"True","chatShoutAllCaps":"False","newDayNumberToggle":"True"},"Toggles.Position":{"chatShoutPosEnabled":"False","chatPingPosEnabled":"True","playerJoinPosEnabled":"False","playerLeavePosEnabled":"False","playerDeathPosEnabled":"True","eventStartPosEnabled":"True","eventStopPosEnabled":"True","eventPausedPosEnabled":"True","eventResumedPosEnabled":"True"},"Toggles.Stats":{"statsDeathEnabled":"True","statsJoinEnabled":"True","statsLeaveEnabled":"True","statsPingEnabled":"True","statsShoutEnabled":"True"},"Toggles.PlayerFirsts":{"announceFirstDeathEnabled":"True","announceFirstJoinEnabled":"True","announceFirstLeaveEnabled":"True","announceFirstPingEnabled":"True","announceFirstShoutEnabled":"True"},"Toggles.DebugMessages":{"debugEveryPlayerPosCheck":"False","debugEveryEventCheck":"False","debugEventChanges":"False","debugDatabaseMethods":"False","debugHttpRequestResponses":"False"}},"Config.Variables":{"User-Defined":{"userVar":"","userVar1":"","userVar2":"","userVar3":"","userVar4":"","userVar5":"","userVar6":"","userVar7":"","userVar8":"","userVar9":""},"Dynamic-Configured":{"posVarFormat":"%X%, %Y%, %Z%","appendedPosFormat":"Coords: (%POS%)"}},"Config.LeaderBoard":{"leaderBoard1":{"enabled":"True","periodInMinutes":600,"displayedHeading":"LeaderBoard.1 Statistic Leader Board","type":"Descending","timeRange":"AllTime","numberListings":3,"deaths":"True","sessions":"True","shouts":"True","pings":"True","timeOnline":"True"},"leaderBoard2":{"enabled":"False","periodInMinutes":600,"displayedHeading":"LeaderBoard.2 Statistic Leader Board","type":"Descending","timeRange":"AllTime","numberListings":3,"deaths":"True","sessions":"False","shouts":"False","pings":"False","timeOnline":"False"},"leaderBoard3":{"enabled":"False","periodInMinutes":600,"displayedHeading":"LeaderBoard.3 Statistic Leader Board","type":"Descending","timeRange":"AllTime","numberListings":3,"deaths":"True","sessions":"False","shouts":"False","pings":"False","timeOnline":"False"},"leaderBoard4":{"enabled":"False","periodInMinutes":600,"displayedHeading":"LeaderBoard.4 Statistic Leader Board","type":"Descending","timeRange":"AllTime","numberListings":3,"deaths":"True","sessions":"False","shouts":"False","pings":"False","timeOnline":"False"},"leaderBoard5":{"enabled":"False","periodInMinutes":600,"displayedHeading":"LeaderBoard.5 Statistic Leader Board","type":"Descending","timeRange":"AllTime","numberListings":3,"deaths":"True","sessions":"True","shouts":"True","pings":"True","timeOnline":"True"},"activePlayersAnnouncement":{"enabled":"True","disableWhenNooneOnline":"False","periodInMinutes":360,"includeCurrentlyOnline":"True","includePlayersToday":"True","includePlayersPastWeek":"True","includePlayersAllTime":"True"}},"Config.ExtraWebhooks":{"webhookURL1": "unset","webhookEvents1": "ALL","webhookUsernameOverride1": "","webhookAvatarOverride1": "","webhookURL2": "unset","webhookEvents2": "ALL","webhookUsernameOverride2": "","webhookAvatarOverride2": "","webhookURL3": "unset","webhookEvents3": "ALL","webhookUsernameOverride3": "","webhookAvatarOverride3": "","webhookURL4": "unset","webhookEvents4": "ALL","webhookUsernameOverride4": "","webhookAvatarOverride4": "","webhookURL5": "unset","webhookEvents5": "ALL","webhookUsernameOverride5": "","webhookAvatarOverride5": "","webhookURL6": "unset","webhookEvents6": "ALL","webhookUsernameOverride6": "","webhookAvatarOverride6": "","webhookURL7": "unset","webhookEvents7": "ALL","webhookUsernameOverride7": "","webhookAvatarOverride7": "","webhookURL8": "unset","webhookEvents8": "ALL","webhookUsernameOverride8": "","webhookAvatarOverride8": "","webhookURL9": "unset","webhookEvents9": "ALL","webhookUsernameOverride9": "","webhookAvatarOverride9": "","webhookURL10": "unset","webhookEvents10": "ALL","webhookUsernameOverride10": "","webhookAvatarOverride10": "","webhookURL11": "unset","webhookEvents11": "ALL","webhookUsernameOverride11": "","webhookAvatarOverride11": "","webhookURL12": "unset","webhookEvents12": "ALL","webhookUsernameOverride12": "","webhookAvatarOverride12": "","webhookURL13": "unset","webhookEvents13": "ALL","webhookUsernameOverride13": "","webhookAvatarOverride13": "","webhookURL14": "unset","webhookEvents14": "ALL","webhookUsernameOverride14": "","webhookAvatarOverride14": "","webhookURL15": "unset","webhookEvents15": "ALL","webhookUsernameOverride15": "","webhookAvatarOverride15": "","webhookURL16": "unset","webhookEvents16": "ALL","webhookUsernameOverride16": "","webhookAvatarOverride16": ""}}`

**Screenshots**
```
valheim-1  | [ODIN][INFO]: [valheim_server.log]: IOException: The file '/home/steam/valheim/BepInEx/config/games.nwest.valheim.discordconnector/vdc.log.old' already exists.
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at System.IO.FileSystem.LinkOrCopyFile (System.String sourceFullPath, System.String destFullPath) [0x000b9] in <5aefc10cb7a348a6a66a4e2036c11d65>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) [0x0003a] in <5aefc10cb7a348a6a66a4e2036c11d65>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00083] in <5aefc10cb7a348a6a66a4e2036c11d65>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at DiscordConnector.VDCLogger.InitializeLogFile () [0x0001c] in <6547d6e3cef040faaba1156b08340824>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at DiscordConnector.VDCLogger..ctor (BepInEx.Logging.ManualLogSource logger) [0x00025] in <6547d6e3cef040faaba1156b08340824>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]:   at DiscordConnector.Plugin..ctor () [0x0000c] in <6547d6e3cef040faaba1156b08340824>:0 
valheim-1  | [ODIN][INFO]: [valheim_server.log]: UnityEngine.GameObject:Internal_AddComponentWithType(GameObject, Type)
```

**Server Environment**
Where are you running the Valheim dedicated server? Personal linux or windows server, a hosting service, directly from your client, etc?

linux server inside docker container (https://github.com/mbround18/valheim-docker) 

```
compose.yml:
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "XXXXXX"
      WORLD: "Dedicated"
      PASSWORD: "XXXXXX"
      TYPE: "BepInEx"
      MODS: "https://gcdn.thunderstore.io/live/repository/packages/JereKuusela-Server_devcommands-1.86.0.zip,
             https://github.com/nwesterhausen/valheim-discordconnector/releases/download/v2.3.2/DiscordConnector.zip"
      TZ: "Europe/Berlin"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 */6 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: "https://discord.com/api/webhooks/XXXXXX"
      WEBHOOK_INCLUDE_PUBLIC_IP: 1
      PLAYER_EVENT_NOTIFICATIONS: 1
      UPDATE_ON_STARTUP: 0
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
    restart: unless-stopped
```

**Installed Mods**
```
      MODS: "https://gcdn.thunderstore.io/live/repository/packages/JereKuusela-Server_devcommands-1.86.0.zip,
             https://github.com/nwesterhausen/valheim-discordconnector/releases/download/v2.3.2/DiscordConnector.zip"
```

**Additional context**
first occurrence during tests why leaderboard does not show up (changed Sending Period to 5 for debugging purposes)
